name: Automation API Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  run-api-automation:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build with Gradle
        run: chmod +x gradlew

      - name: Execute API Test
        run: ./gradlew clean test

      - name: Archive test result
        uses: actions/upload-artifact@v4.3.0
        if: always ()
        with:
          name: cucumber
          path: reports/cucumber-api-report.html


